apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-app
  labels:
    team : billing-app-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      containers:
        - name: billing-service
          image: syr7s/billing-service:v1
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "768m"
          ports:
            - containerPort: 8085
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 15
            periodSeconds: 20

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
  labels:
    team : customer-app-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
        - name: customer-service
          image: syr7s/customer-service:v1
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "768m"
          ports:
            - containerPort: 8090
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8090
            initialDelaySeconds: 15
            periodSeconds: 20
        
          
