version: "3.8"
services:
  customer-service:
    image: syr7s/customer-service:v1
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
    ports:
      - "8090:8090"
    networks:
      - micro-service

  billing-service:
    depends_on:
      - customer-service:v1
    image: syr7s/billing-service:v1
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
    ports:
      - "8085:8085"
    networks:
      - micro-service

networks:
  micro-service:
    driver: overlay