apiVersion: v1
kind: Service
metadata:
  name: billing-app
  labels:
    app: billing-app
spec:
  type: NodePort
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
  selector:
    app: billing-app

---
apiVersion: v1
kind: Service
metadata:
  name: customer-app
  labels:
    app: customer-app
spec:
  type: NodePort
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: customer-app